<?php
namespace FuriosoJack\Kaseravel\Tests;
use Codwelt\HelpersMan\laravel\HelperManProvider;
use FuriosoJack\LaraException\Providers\LaraExceptionServiceProvider;
use Orchestra\Testbench\BrowserKit\TestCase as TestFather;

/**
 * Class TestCase
 * @author Juan Diaz - FuriosoJack <iam@furiosojack.com>
 */
class TestCase extends TestFather
{

    public function getPackageProviders($app)
    {
        return [
          HelperManProvider::class,
          LaraExceptionServiceProvider::class
        ];
    }

    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub

    }

    /**
     * Disabled test
     *
     */
    public function authBasic()
    {
        $clientAPi = new Auth("saas19.pccor.net","user",'passs');
        $this->response =  $clientAPi->get('/system/users');

        $this->assertResponseStatus(0);

        $userID = "74893716";
        $this->response =  $clientAPi->get('/system/users/'.$userID);

        $this->assertResponseStatus(0);


        $this->response = $clientAPi->get('/assetmgmt/agents');
        $this->assertResponseStatus(0);


        $url = '/system/users/' . $userID . '/disabled';
        $response = $clientAPi->put($url);
        dd($response);


    }

}